### ISSUE TITLE
don't sort "asciibetical"

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/contributors#19]
The current sort puts all caps first, then all lower case later, then non-ascii stuff at the end. We should do a real sort instead.

**Comment by lfairy** [comment]
The ideal solution would be to use the [default Unicode collation order](http://unicode.org/reports/tr10/), which was designed for this purpose. But I couldn't find any existing crate that implements that.

A second-best solution would be to [case fold](http://stackoverflow.com/q/40250988/617159) and decompose the strings, strip any accent characters, and compare the results. That would work okay for European languages but fail for pretty much anything else.

**Comment by Taneb** [comment]
My fork has been altered so that it uses icu. However, for fairly stupid reasons, I can't test it. So, if someone will confirm it works as intended, I'll send a pull request.

Note also that I've bound the bare minimum necessary for this purpose. I'm going to be slowly working on completing the bindings, however.

**Comment by ThatOtherPerson** [comment]
There were a couple of typos: https://github.com/Taneb/contributors/pull/1. More importantly, it currently requires you to install ICU separately, and the foreign function calls refer to a specific version of ICU, such as ICU 52 in `ucol_open_52`. Would it make sense to do something like what servo/rust-icu does in the build script: https://github.com/servo/rust-icu/blob/master/icu-sys/build.rs?
